Synomy/Components/AdminNavBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Synomy.Components
{
    public class AdminNavBarViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Run(() => {
                return View();
            });
        }
    }
}

Synomy/Components/NavigationBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Synomy.Components
{
    public class NavigationBarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke() => View();
    }
}

Synomy/Controllers/TopicsController.cs
using Microsoft.AspNetCore.Mvc;
using Synomy.Models.ViewModels;
using System.Linq;
using System.Collections.Generic;
using Synomy.Models.Api;
using System.Threading.Tasks;
using Synomy.Services;
using System.Web;
using Synomy.Models.Application;

namespace Synomy.Controllers
{
    public class TopicsController : Controller
    {
        private IHttpClient notusClient;
        private IFavorites favorites;

        public TopicsController(IHttpClient notusClient, IFavorites favorites)
        {
            this.notusClient = notusClient;
            this.favorites = favorites;
        }

        public int PageSize = 5;

        public async Task<IActionResult> Index() =>
            View("List", CreateLanguageTopicCardList(await notusClient.GetDataICollection<LanguageTopicDTO>("LanguageTopic"), "Title", "All"));

        public async Task<IActionResult> AllByTitle(int topicPage = 1) =>
            View("List", CreateLanguageTopicCardList(await notusClient.GetDataICollection<LanguageTopicDTO>($"LanguageTopic/Topic"), "Title", "All", topicPage));

        public async Task<IActionResult> Title(string filter, int topicPage = 1) =>
            View("List", CreateLanguageTopicCardList(await notusClient.GetDataICollection<LanguageTopicDTO>($"LanguageTopic/Topic/{filter}"), "Title", filter, topicPage));

        public async Task<IActionResult> Language(string filter, int topicPage = 1) =>
            View("List", CreateLanguageTopicCardList(await notusClient.GetDataICollection<LanguageTopicDTO>($"LanguageTopic/Language/{HttpUtility.UrlEncode(filter)}"), "Language", filter, topicPage));

        public async Task<IActionResult> TitleToggle() =>
            View("List", CreateLanguageTopicCardList(await notusClient.GetDataICollection<LanguageTopicDTO>("LanguageTopic"), "Title", "All"));

        private CardListViewModel<Card> CreateLanguageTopicCardList(ICollection<LanguageTopicDTO> data, string filterType = null, string filter = null, int topicPage = 1) =>
            new CardListViewModel<Card>
            {
                CardType = CardType.Default,
                Data = data.Skip((topicPage - 1) * PageSize).Take(PageSize)
                .Select(item => new Card
                {
                    CardType = CardType.Default,
                    Content = ContentUtilities.CreateContent(item),
                    IsFavorited = favorites.InFavorites(item.LanguageTopicId, "LanguageTopic")
                }),
                Controller = RouteData.Values["controller"].ToString(),
                FilterType = filterType,
                FilterValue = filter,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = topicPage,
                    ItemsPerPage = PageSize,
                    TotalItems = data.Count
                }
            };
    }
}

Synomy/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Synomy.Infrastructure;
using Synomy.Services;
using System.Threading.Tasks;

namespace Synomy.Controllers
{
    [UserFilter]
    public class UserController : Controller
    {
        private IUserService userService { get; set; }

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }

        [Authorize]
        public async Task<IActionResult> Index() =>
            await Task.Run(() => View(userService));

        [AllowAnonymous]
        public async Task Login() =>
            await HttpContext.ChallengeAsync("oidc", new AuthenticationProperties
            {
                RedirectUri = Url.Action("Index")
            });

        [Authorize]
        public async Task Logout()
        {
            await HttpContext.SignOutAsync("Cookies");
            await HttpContext.SignOutAsync("oidc");
        }
    }
}

Synomy/Views/Shared/_AdminLayout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="Synomy">
    <meta name="author" content="William McCullough">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
    <link rel="stylesheet" asp-href-include="/styles/min.min.css" />
    <script asp-src-include="/js/admin.bundle.js"></script>
</head>

<body>

    @await Component.InvokeAsync("AdminNavBar")

    @await Component.InvokeAsync("Sidebar")

    <div class="container-fluid">
        <div class="row m-1 p-1">

            <div id="categories" class="nav-menu col-3">
                <div class="list-group">
                    @await Component.InvokeAsync("NavigationMenu")
                </div>
            </div>

            <div class="render-body cold-xs-12 col-lg-9">
                @RenderBody()
            </div>

        </div>
    </div>

</body>

</html>

Synomy/Views/Shared/_GuestLayout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="Synomy">
    <meta name="author" content="William McCullough">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
    <link rel="stylesheet" asp-href-include="/styles/min.min.css" />
    <script asp-src-include="/js/main.bundle.js"></script>
</head>

<body>

    @{
        IgnoreBody();
    }

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <div class="display-4">
                <div class="jumbo-icon-container">
                    <i class="jumbo-icon material-icons">chevron_left</i><span>SYNOMY</span><i class="jumbo-icon material-icons">chevron_right</i>
                 </div>
            </div>
            <p class="lead">A free and intuitive way to manage your notes</p>
            <hr class="my-4">
            <p>
                Synomy is a part of the Okami Services ecosystem. Please create an account if you 
                would like to join our community, or feel free to browse without one.
            </p>
            <p class="lead">
                <a asp-controller="User" class="btn btn-primary btn-lg" role="button">Sign In</a>
                or
                <a disabled class="btn btn-primary btn-lg" href="#" role="button">Sign Up</a>
            </p>
            <p class="lead">   
                <a asp-controller="Topics" class="btn btn-success btn-lg" role="button">Browse</a>
            </p>
        </div>
    </div>

</body>

</html>

Synomy/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="Synomy">
    <meta name="author" content="William McCullough">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
    <link rel="stylesheet" asp-href-include="/styles/min.min.css" />
    <script asp-src-include="/js/main.bundle.js"></script>
</head>

<body>
    <div class="wrapper">

        @await Component.InvokeAsync("NavigationBar")

        @await Component.InvokeAsync("Sidebar")

        <div id="content">
            <div class="container-fluid">
                <div class="row m-1 p-1">
                    <div id="categories" class="nav-menu col-3">
                        <div class="list-group">
                            @await Component.InvokeAsync("NavigationMenu")
                        </div>
                    </div>

                    <div class="render-body cold-xs-12 col-lg-9">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>

    </div>
</body>

</html>